[build]
builder = "nixpacks"
buildCommand = "cd ihm-frontend && npm install && npm run build"

[deploy]
startCommand = "cd ihm-frontend && npm run preview"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
